#!/bin/bash

SCRIPT_FOLDER=$(dirname "$0")

. "${SCRIPT_FOLDER}/intellij_common"

checknode
setupsdk
licensing

cachemodules $@

copylibs
setuplibs

if [ "" == "$(which mvn)" ]; then
    "$NODEJS" "${SCRIPT_FOLDER}/bin/run.js" "$PWD" "$@"
else
    "$NODEJS" "${SCRIPT_FOLDER}/bin/run.js" "$PWD" "$@" --mvn-cache=true
fi

uncachemodules $@

ignoreiml

enabledebug