#!/bin/bash

if [ -d modules ] && [ ! -d tools/sdk ]; then
	if [ -f "lib/portal/dependencies.properties" ]; then
		ant setup-sdk setup-libs
	else
		ant setup-sdk
	fi
fi

node $(dirname $0)/streams0/bin/run.js $PWD $@

git ls-files | grep '\(\.idea\|\.iml\)' | xargs git update-index --assume-unchanged