#!/bin/bash

gradlewidea() {
	if [ ! -e .git ]; then
		echo "Unable to run gradlew idea outside of portal source"
		return 1
	fi

	cat /dev/null > .idea/projects.txt

	for folder in $(git ls-files modules | grep build.gradle | grep -v gradleTest | grep -v archetype-resources | xargs -I {} dirname {}); do
		if [ -d $folder/src/main/java ]; then
			echo $folder | cut -d'/' -f 2- >> .idea/projects.txt
		fi
	done

	GRADLE_OPTS='-Xms3g -Xmx3g -Dorg.gradle.workers.max=1'

	if [[ 8 -gt $JAVA_VERSION ]]; then
		GRADLE_OPTS="$GRADLE_OPTS -XX:MaxPermSize=512m"
	fi

	export GRADLE_OPTS

	pushd modules > /dev/null

	if [ "eclipse" == "$1" ]; then
		cat ../.idea/projects.txt | tr '/' ':' | awk '{ print ":" $1 ":eclipse" }' | xargs ../gradlew --continue
	else
		cat ../.idea/projects.txt | tr '/' ':' | awk '{ print ":" $1 ":idea" }' | xargs ../gradlew --continue
	fi

	popd > /dev/null
}

. $(dirname ${BASH_SOURCE[0]})/intellij_common

if [ ! -d modules ]; then
	echo 'gradlew is not available in this Liferay source folder'
	exit 1
fi

setupsdk
copylibs
setuplibs

gradlewidea $@