#!/bin/bash

setantopts() {
	JAVA_VERSION=$(java -version 2>&1 | head -1 | cut -d'"' -f 2 | cut -d'.' -f 2)

	ANT_OPTS='-Xms2g -Xmx2g'

	if [[ 8 -gt $JAVA_VERSION ]]; then
		ANT_OPTS="$ANT_OPTS -XX:MaxPermSize=1g"
	fi

	export ANT_OPTS
}

NODEJS=$(which nodejs 2> /dev/null)

if [ "" == "$NODEJS" ]; then
	NODEJS=$(which node 2> /dev/null)
fi

if [ "" == "$NODEJS" ]; then
	echo "Please install node.js"
	exit 1
fi

pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null

echo 'Running npm/yarn to update script dependencies'

if [ "" != "$(which yarn 2> /dev/null)" ]; then
	yarn
else
	npm install
fi

popd > /dev/null

if [ ! -f release.properties ]; then
	echo 'Please run this script from a Liferay source folder'
	echo 'Arguments are additional source roots (blade workspaces, subrepositories, plugins SDK, etc.)'
	exit 1
fi

if [ -d modules ] && [ ! -d tools/sdk ]; then
	setantopts

	echo 'Running ant setup-sdk to initialize gradle configuration'

	ant setup-sdk
fi

if [ -f "lib/portal/dependencies.properties" ]; then
	if [[ $(ls -1 "lib/portal" | wc -l) -lt $(cat "lib/portal/dependencies.properties" | wc -l) ]]; then
		setantopts

		echo 'Running ant setup-libs to initialize portal libraries'

		ant setup-libs
	fi
fi

"$NODEJS" $(dirname $0)/streams0/bin/pom.js $PWD $@
mvn dependency:sources
grep '<module>.*</module>' pom.xml | awk -F'[<>]' '{ print $3 "/pom.xml" }' | xargs rm
rm pom.xml

"$NODEJS" $(dirname $0)/streams0/bin/run.js $PWD $@

git ls-files | grep '\(\.idea\|\.iml\)' | xargs git update-index --assume-unchanged