#!/bin/bash

SCRIPT_FOLDER=$(dirname "$0")

. "${SCRIPT_FOLDER}/intellij_common"

checknode
setupsdk
copylibs
setuplibs

"$NODEJS" "${SCRIPT_FOLDER}/bin/pom.js" "$PWD" $@

mvn  --fail-at-end dependency:sources
grep '<module>.*</module>' pom.xml | awk -F'[<>]' '{ print $3 "/pom.xml" }' | xargs rm
rm pom.xml

"$NODEJS" "${SCRIPT_FOLDER}/bin/run.js" "$PWD" "$@"

ignoreiml