#!/bin/bash

if [ -d modules ] && [ ! -d tools/sdk ]; then
	JAVA_VERSION=$(java -version 2>&1 | head -1 | cut -d'"' -f 2 | cut -d'.' -f 2)

	ANT_OPTS='-Xms2g -Xmx2g'

	if [[ 8 -gt $JAVA_VERSION ]]; then
		ANT_OPTS="$ANT_OPTS -XX:MaxPermSize=1g"
	fi

	export ANT_OPTS

	if [ -f "lib/portal/dependencies.properties" ]; then
		ant setup-sdk setup-libs
	else
		ant setup-sdk
	fi
fi

if [[ -n "$WINDIR" ]]; then
	pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null

	for target_file in $(git ls-files -s | grep '^120000' | awk '{ print $4 }'); do
		rm $target_file
		source_file=$(git ls-files -s | grep -F $(basename $target_file) | grep -v '^120000' | awk '{ print $4 }' | sort -u | tail -1)
		cp $source_file $(dirname $target_file)
	done

	popd > /dev/null
fi

node $(dirname $0)/streams0/bin/pom.js $PWD $@
mvn dependency:sources
grep '<module>.*</module>' pom.xml | awk -F'[<>]' '{ print $3 "/pom.xml" }' | xargs rm
rm pom.xml

node $(dirname $0)/streams0/bin/run.js $PWD $@

if [[ -n "$WINDIR" ]]; then
	pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null

	for target_file in $(git ls-files -s | grep '^120000' | awk '{ print $4 }'); do
		rm $target_file
		git checkout $target_file
	done

	popd > /dev/null
fi

git ls-files | grep '\(\.idea\|\.iml\)' | xargs git update-index --assume-unchanged